apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: my-github-runner
  namespace: actions-runner-system
spec:
  template:
    spec:
      repository: "PushpaH/AKSRunner"
      labels:
        - "self-hosted"
        - "linux"
        - "kubectl"
      env:
        - name: GITHUB_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-access-token
              key: token
      resources:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "1"
          memory: "2Gi"
